# Generated by Django 4.0.6 on 2022-11-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Showroom', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/products/'),
        ),
    ]
